version: '3.8'

services:
  org:
    build:
      context: .
      dockerfile: ./apps/org/Dockerfile
      target: development
    command: pnpm run start:dev org
    container_name: buidl_org
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - ./apps/org/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - buidl_net

  # Infra
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - buidl_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - buidl_net

  redis:
    image: redis
    container_name: buidl_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - buidl_adapter:/data
    networks:
      - buidl_net

volumes:
  buidl_data:
    name: buidl_data
  buidl_broker:
    name: buidl_broker
  buidl_adapter:
    name: buidl_adapter
  buidl_es_data:
    name: buidl_es_data
  buidl_pg_admin_data:
    name: buidl_pg_admin_data

networks:
  buidl_net:
    name: buidl_net
    driver: bridge
